# Generated by Django 4.2.21 on 2025-05-07 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='is_double',
        ),
        migrations.CreateModel(
            name='PoolWeekSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_double', models.BooleanField(default=False)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_settings', to='pool.pool')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_settings', to='pool.week')),
            ],
        ),
        migrations.AddField(
            model_name='pool',
            name='weeks',
            field=models.ManyToManyField(related_name='pools', through='pool.PoolWeekSettings', to='pool.week'),
        ),
        migrations.AddConstraint(
            model_name='poolweeksettings',
            constraint=models.UniqueConstraint(fields=('pool', 'week'), name='unique_week_settings_per_pool'),
        ),
    ]
