# Generated by Django 4.2.21 on 2025-05-07 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pool', '0002_remove_week_is_double_poolweeksettings_pool_weeks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WeeklyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('tie', 'Tie')], max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the game/result')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.team')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pool.week')),
            ],
            options={
                'ordering': ['week', 'team__city'],
            },
        ),
        migrations.AddConstraint(
            model_name='weeklyresult',
            constraint=models.UniqueConstraint(fields=('week', 'team'), name='unique_team_result_per_week'),
        ),
    ]
