# Generated by Django 4.2.21 on 2025-05-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0003_alter_auditlog_user_weeklyresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
