# Generated by Django 4.2.21 on 2025-05-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0004_week_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='week',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
